fixes + ignore working copy if empty + show year in sidebar items + more infos when no text changes + scroll on move
- updating the start/end markers position with alt/ctrl is not working
- the "focus diff" breaks styling, i think the container doesnt stretch to the full width/height (see screen4)
- currently we default to showing the diff vs working tree (git) / working copy (jj), but we should NOT do that IF there are NO changes impacting the selected file; it should not even be part of the timeline if thats not the case
- in the sidebar items it would be nice to show the year along with the month+day
- when moving the revision range with left/right we should also scroll (in the sidebar items) to the corresponding start of the range
- we should have a way to search in the sidebar items (by commit name/description/author), probably with something in the top of the sidebar (below the title tho, right before the sidebar items)
- when there are "no textual changes" then it would be nice to show WHAT changed? filename? line ending? something else?
- IF the filename was changed (e.g the file was moved) AND our version engine (git/jj) know about it then we should also display diffs based on those earlier file names (and not just on the current filename/path)
- seems like i got an issue when trying to see the timeline of a file (screen1), here's the log:
Command failed: jj log --no-graph --limit 200 -T commit_id.short() ++ "\t" ++ change_id.shortest() ++ "\t" ++ author.timestamp().format("%Y-%m-%dT%H:%M:%S%:z") ++ "\t" ++ description.first_line() ++ "\n" apps/frontend/src/routes/_auth/$organization/purchase-requests/$purchaseRequest/edit.tsx
Error: Failed to parse fileset: Syntax error
Caused by:  --> 1:32
|
1 | apps/frontend/src/routes/_auth/$organization/purchase-requests/$purchaseRequest/edit.tsx
|                                ^---
Command failed: jj log --no-graph --limit 200 -T commit_id.short() ++ "\t" ++ change_id.shortest() ++ "\t" ++ author.timestamp().format("%Y-%m-%dT%H:%M:%S%:z") ++ "\t" ++ description.first_line() ++ "\n" apps/frontend/src/routes/_auth/$organization/purchase-requests/$purchaseRequest/edit.tsx
Error: Failed to parse fileset: Syntax error
Caused by:  --> 1:32
|
1 | apps/frontend/src/routes/_auth/$organization/purchase-requests/$purchaseRequest/edit.tsx
|                                ^---